### ISSUE TITLE
no option to enable `trust_remote_code=True`

### ISSUE THREAD

**Issue by OmarQuishawi** [AbdelRahmanYaghi/internalTools#1]
I was using the load_model function and I passed the model name into it and it gave me the following error :

ValueError: Loading dunzhang/stella_en_400M_v5 requires you to execute the configuration file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.

I am running the notebook inside a docker container using python 3.11.9 on WSL , Below is the code to reproduce the error:

`from internalTools.modeling import load_model`
`model = load_model('dunzhang/stella_en_400M_v5')`

**Comment by AbdelRahmanYaghi** [comment]
Hello Omar,

this issue has been solved in the latest update, i.e., 0.0.4.1, where you can add any arguments you wish in the load_model function. Please find the code below.

```
from internalTools.modeling import load_model

model = load_model('dunzhang/stella_en_400M_v5', trust_remote_code = True)
```
